project:
  type: website
  output-dir: docs

website:
  title: "Krum Arnaudov"
#  site-url: https://mm218.dev
  description: "Krum Arnaudov's Blog"
  twitter-card:
    creator: "@ArnaudovKrum"
  comments:
    utterances:
      repo: krumeto/krums_blog
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Presentations"
        href: presentations
      - text: "Blog"
        href: blog.html
      - icon: rss
        href: blog.xml
  page-footer:
    left: "© Copyright 2023 Krum Arnaudov. Except where otherwise noted, all text and images licensed CC-BY-NC 4.0."
  cookie-consent: true
format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css